

# Code Book: Week 4 Getting And Cleaning Data Course Project
Contains Additional Information regarding Data-Set used in course project.
Further details can be found in the readme.txt file located in the following download (Note this includes complete data set as well):

https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip


## Overview of Data

An experiement, 'Human Activity Recognition Using Smartphones Data Set', carried out by UC Irvine to create a Human Activity Recognition database built from the recordings of 30 subjects performing activities of daily living (ADL) while carrying a waist-mounted smartphone with embedded inertial sensors.

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

##Description of information provided in Data-Set

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration. 
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who participated in the experiment.

## Script Overview:

#### 1. Reads & Writes tables from the downloaded .zip file utilizing the following files:

* features.txt
* activity_labels.txt
* subject_train.txt
* x_train.txt
* y_train.txt
* subject_test.txt
* x_test.txt
* y_test.txt

#### 2. Combines train/test data-sets into respective variables:

*subject
*activity
*features

#### 3. Assigns column names and merge to create one data set

#### 4. Pulls Mean and Standard Deviation for each measurement

#### 5. Assigns appropriate Descriptive Names to Activity Fields

#### 6. Restructures Syntax for Clarity while reading using logical syntax as well as removing superfluous characters

#### 7. As per instructions creates and writes a tidy data 'tidy_data.txt' to working directory
* Tidy data set contains only the average for each variable, of each activity, for each subject








